name: curl \
  -H 'Content-Type: application/json' \
  -d '{"contents":[{"parts":[{"text":"Explain how AI works"}]}]}' \
  -X POST 'https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent?
on:
  push:
    branches: [ main ]
    paths:
    - 'Sources/Core/**'
    - 'Sources/GeneratedServices/Discovery/**'
    - 'Tools/**'
    - '!Tools/**/*.md'
    - '!Tools/**/*.py'
    - '!Tools/GenerateCheckedInServices*'
    - 'Package*.swift'
    - '.github/workflows/service_generator.yml'
  pull_request:
    branches: [ main ]
    paths:
    - 'Sources/Core/**'
    - 'Sources/GeneratedServices/Discovery/**'
    - 'Tools/**'
    - '!Tools/**/*.md'
    - '!Tools/**/*.py'
    - '!Tools/GenerateCheckedInServices*'
    - 'Package*.swift'
    - '.github/workflows/service_generator.yml'
  schedule:
    # Run the first and fifteenth of every month at 6:32 UTC
    - cron:  '32 6 1,15 * *'

jobs:
  swift:
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        CONFIGURATION: ["debug", "release"]
    steps:
    - uses: actions/checkout@v4
    - name: Build ServiceGenerator
      run:  |
        set -eu
        cd Tools
        swift build --configuration ${{ matrix.CONFIGURATION }}

  xcodebuild:
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        CONFIGURATION: ["Debug", "Release"]
    steps:
    # The "macos-14" image defaults to 15.0.1, select the newer Xcode.
    - name: Xcode version
      run: sudo xcode-select -switch /Applications/Xcode_15.2.app
    - uses: actions/checkout@v4
    - name: Build ServiceGenerator
      run:  |
        set -eu
        cd Tools
        set -o pipefail
        xcodebuild \
            -scheme GTLR_ServiceGenerator \
            -configuration ${{ matrix.CONFIGURATION }} \
            -destination "platform=macOS" \
            build \
          | xcpretty
