name: SwiftPM

on:
  push:
    branches: [ main ]
    paths:
    - 'Sources/**'
    - 'UnitTests/**'
    - 'Package*.swift'
    - 'SwiftPMTests/**'
    - '.github/workflows/swiftpm.yml'
  pull_request:
    branches: [ main ]
    paths:
    - 'Sources/**'
    - 'UnitTests/**'
    - 'Package*.swift'
    - 'SwiftPMTests/**'
    - '.github/workflows/swiftpm.yml'
  schedule:
    # Run the first and fifteenth of every month at 6:12 UTC
    - cron:  '12 6 1,15 * *'

jobs:
  swift:
    # The swift command line only support build/testing for macOS on.
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        CONFIGURATION: ["debug", "release"]
    steps:
    - uses: actions/checkout@v4
    - name: Build and Test Library
      run:  |
        set -eu
        swift build --configuration ${{ matrix.CONFIGURATION }}
        swift test --configuration ${{ matrix.CONFIGURATION }}

  xcodebuild:
    # Job(s) to build for all the platforms to ensure that is working and the
    # tests are passing.
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        PLATFORM: ["ios", "macos", "tvos", "watchos"]
        CONFIGURATION: ["Debug", "Release"]
    steps:
    - uses: actions/checkout@v4
    - name: Build and Test Library
      run:  |
        set -eu
        case "${{matrix.PLATFORM}}" in
          ios)
            DESTINATION="platform=iOS Simulator,name=iPhone 8,OS=latest"
            ;;
          macos)
            DESTINATION="platform=macOS"
            ;;
          tvos)
            DESTINATION="platform=tvOS Simulator,name=Apple TV,OS=latest"
            ;;
          watchos)
            DESTINATION="platform=WatchOS Simulator,name=Apple Watch Series 7 (45mm),OS=latest"
            ;;
        esac

        set -o pipefail
        xcodebuild \
            -scheme GoogleAPIClientForREST-Package \
            -configuration ${{ matrix.CONFIGURATION }} \
            -destination "${DESTINATION}" \
            build test \
          | xcpretty
